### ISSUE TITLE
list out of range

### ISSUE THREAD

**Issue by maomaocn** [dannluciano/django-miniexplorer#4]
执行的sql语句如果没有结果返回，程序就会报错  
更新一下下面的这个方法，即可解决
def change_view(self, request, object_id, form_url="", extra_context=None):
        extra_context = extra_context or {}
        query = get_object_or_404(Query, pk=object_id)
        time = timezone.now()
        results = query.execute()
        fields = results[0]._fields if results else []
        extra_context["results"] = results
        extra_context["fields"] = fields
        extra_context["last_time"] = time
        return super().change_view(
            request,
            object_id,
            form_url,
            extra_context=extra_context,
        )

**Comment by dannluciano** [comment]
Thanks

**Comment by dannluciano** [comment]
Try the last version: https://pypi.org/project/django-miniexplorer/0.5.0/
